name: Build MultiSense ROS

on:
  push:
    branches:
      - master
  release:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref_name }}-build
      cancel-in-progress: ${{ github.ref_name != 'main' }}
    strategy:
      fail-fast: false
      matrix:
        ros_distro:
          - noetic
          - melodic
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          build-args: |
            ros_codename=${{ matrix.ros_distro }}
